- docs/wiki/baseclasses.md
- jumpscale/clients/stellar/stellar.py
- jumpscale/core/base/fields.py
- jumpscale/core/base/meta.py
- tests/core/base/test_factory.py
- tests/core/base/test_fields_with_base.py
- tests/core/base/test_stored_factory.py
Added:
- `on_update`: for single-field updates
- `compute`: for computed fields
- `stored`: to control if you need this fields to be stored or not
Updated the docs too [here](https://github.com/js-next/js-ng/blob/9557df05ba1ba938f8f4865e9367ecd5d10615ea/docs/wiki/baseclasses.md).
> fields: simpler updates handling and non-stored fields

- jumpscale/clients/explorer/__init__.py
- jumpscale/clients/explorer/explorer.py
Fixes https://github.com/js-next/js-ng/issues/277.
The explorer url was None because it was not provided and it was not a required argument so, it should be a required argument on explorer client creation
> Requiring url argument on creating explorer client

- .travis.yml
- docs/api/jumpscale/core/base/factory.html
- docs/wiki/configmgmt.md
- docs/wiki/stores.md
- jumpscale/core/base/factory.py
- jumpscale/entry_points/jsctl.py
Resolves  #390.
Receive config get and update as arguments rather than options.
Allow accessing and modifying nested properties.
> Change config options to arguments and allow nesting

- jumpscale/core/config/config.py
Get version from package metatdata, according to https://github.com/python-poetry/poetry/issues/273 and https://packaging.python.org/guides/single-sourcing-package-version/#single-sourcing-the-package-version.
This will make `pyproject.toml` as single source for package versioning.
Change `core/config.py` version to be set from package metadata and expose it too.
None
> config: get version from metadata

- jumpscale/core/config/config.py
- jumpscale/entry_points/jsng.py
- pyproject.toml
Bump version to 11.0b5 and add version option to `jsng` entry point.
`core/config.py` and `jsng.py` entry point.
> version 11.0b5

- jumpscale/tools/alerthandler/alerthandler.py
Fix find method filtering in alerthandler. lowercase is used in search parameter but not in alerts saved in db.
Added tolower() to the db strings when comparing
https://github.com/threefoldtech/js-ng/issues/470
> Fix find method filtering in alerthandler

- jumpscale/tools/errorhandler/errorhandler.py
Retrieve from the alertandler tools traceback and stacktrace of the last exception to be able to add in alerts raised if needed by adding a helper in error handler
Add helper to get the traceback to be used individually from alertshandler and errorshandler
https://github.com/threefoldtech/js-sdk/issues/1639
> Add get traceback helper in error handler to be used elsewhere

- jumpscale/tools/alerthandler/alerthandler.py
- tests/tools/alerthandler/alerthandler.py
Adds support for custom alert handlers
> Adds support for custom alerthandlers

- .github/workflows/jsng-ci.yml
Using the setup-python action is the recommended way of using Python with GitHub Actions because it ensures consistent behavior across different runners and different versions of Python, instead of using The default version that may vary between GitHub-hosted runners, which may cause unexpected changes or to use an older version than expected.
1- switch from using the default version set in `PATH` to use setup-python action with configured matrix, to run the workflow on a variety of Python versions. more specific python 3.6, 3.7 and 3.8 
2- discard pip3 and venv from being installed as dependencies, as both are part of the Python standard library since 3.3 and 3.4 releases and we only run the workflow on 3.6+ 
> chore: Modify workflow at jsng-ci.yml to run tests with a variety of Python versions

- .github/workflows/jsng-ci.yml
as currently, our CI build fails on ubuntu 20.04, this PR makes these changes to our workflow (fix the issue and also introduce important improvements):
- running ci workflow on Ubuntu 18.04 instead of ubuntu-latest, so CI build will not break when soon github-hosted runner servers switch to use ubuntu 20.04 as latest. see #535 and #540
- including additional matrix values into combinations. ubuntu 20.04 and python 3.9 as only experimental jobs (provides us with insight about the code compatibility) as Experimental testing is crucial for verifying and validating the results of all our development efforts and the current compatibility and back-compatibility status of the project.
- Prevents a workflow run from failing when an experimental job fails (ubuntu 20.04 and python 3.9).
- prevent …
> Update jsng-ci.yml to use multiple ubuntu versions

- tests/sals/process/test_process.py
Add wait for python simple server to start
Change the ports for python simple server until we have a method to get free ports
> Fix failing tests

- jumpscale/sals/fs/__init__.py
add Support to append mode for writing files in sal fs
closes #471
- add new arg to existing functions write_text and write_bytes:
```
def write_text(path: str, data: str, encoding=None, append=False):
...
def write_bytes(path: str, data: bytes, append=False):
...
```
append arg, by default, is False, so the function behavior is the same as before and any old code that uses this function would still work normally. 
If a file does not exist, the function will create a new file. If the file exists it truncates the file unless append arg is set to True.
under the hood, `Path().write_text` and `Path().write_binary` was replaced with `Path().open` to support more file modes.
#471
> Support append mode in writing files in sal fs

- jumpscale/tools/git/__init__.py
- fix `find_git_path` method in git tools
- https://github.com/threefoldtech/js-sdk/issues/2274
> fix find_git_path method in git tools

- .github/workflows/jsng-ci.yml
- jumpscale/core/base/factory.py
- jumpscale/core/base/store/etcd.py
- jumpscale/core/config/config.py
- poetry.lock
- pyproject.toml
- tests/core/base/test_store_mongo.py
- tests/core/base/test_stored_factory.py
Add etcd backend as a config manager
- Add optional etcd3 python package
- Add etcd3 backend as config manager
- Add etcd3 in tests for stored factories
#544
> ETCD backend as config manager

- jumpscale/core/executors/local.py
- jumpscale/core/executors/remote.py
- jumpscale/core/executors/tmux.py
Add a docstring to ```RemoteExecutor``` class 
https://github.com/threefoldtech/js-ng/issues/380
> Update and cleanup executors docstrings

- .github/workflows/jsng-ci.yml
fixing issue #572 with js-ng current workflow, the problem was `setup-python` github action sets a new python Installation for the current user `runner` while using `sudo` with pip makes poetry get installed for default `root` Python installation that comes preinstalled with the system, which in the case of ubuntu 18, was 3.6.
verifying that the issue solved from the actions job log:
**with 3.8**
```
============================= test session starts ==============================
platform linux -- Python 3.8.7, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /home/runner/work/js-ng/js-ng/.venv/bin/python3
```
**with 3.7**
```
============================= test session starts ==============================
platform linux -- Python 3.7.10, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- …
```
> fixing issue#572

- docs/api/jumpscale/sals/index.html
- docs/api/jumpscale/sals/process/index.html
- jumpscale/sals/process/__init__.py
- tests/sals/process/test_process.py
sals.process cleanup/refactor
- Fixing related issues and bugs #467, #557, #561.
- Refactoring and enhancing the module.
- Re-implementing some functions, removing the `ps` shell command completely, and depend on [psutil](https://psutil.readthedocs.io/en/latest/) instead.
- Many functions enriched with new args, and become more generic
- Ensuring complete docstring and matching [google style](https://google.github.io/styleguide/pyguide.html).
- Adding proper error handling.
- Adding proper logging.
- Remove redundant code, unused import, etc.
- Adding a new function kill_proc_tree() to kill all subprocesses that could have been spawn from a given process.
- Adding a new function kill_all_pids() to kill all processes in a given list of PIDs
- Adding more examples in the module docstring.
- …
> sals.process cleanup/refactor

- jumpscale/core/config/config.py
- jumpscale/core/logging/__init__.py
- jumpscale/core/logging/logging.py
Allow enabling/disabling default loguru stderr handler and setting its level.
- Add default config for default logger
- Re-add default handler with the new level
None
> support configuring default logger

- tests/clients/redis/test_redis.py
- tests/sals/process/test_process.py
While running the Redis test suite it tries to find a random port for redis-server using the python `random` module. using this method it is possible to get an already used port and the test will then fail.
to get a free port properly we should bind to port 0 to make the OS pick a random available port from 1024 to 65535.
- switch to use the nettools's `get_free_port` function.
> Improvement to random port allocation for redis testing

- jumpscale/sals/process/__init__.py
remove lower level debug logs from process sal
closes #575
> remove lower level debug logs from process sal

- .github/workflows/jsng-ci-macos.yml
initial macOS workflow for js-ng that installs the dependencies, installs the project, and runs our unit tests.
it will run only when manually triggered.
#593
> initial macos workflow for js-ng

- jumpscale/tools/git/__init__.py
removing the usage of git built-in --sort option as it is not available in git < 2.18. the sort Linux command was used instead.
ATM the git version used in our VDC deployer is 2.17
> improving get_latest_remote_tag() in git module

- .github/workflows/black-docstr.yml
fix empty files for black command
black action
> fix black actions
