- .travis.yml
- jumpscale/core/config/config.py
generate a test private key for configuration management.
> update travis to generate a key before running tests

- jumpscale/core/exceptions/exceptions.py
- jumpscale/data/treemanager/__init__.py
- jumpscale/data/treemanager/exceptions.py
- jumpscale/data/treemanager/treemanager.py
- tests/data/treemanager/test_treemanager.py
Implementation of tree manager.
> Tree manager

- README.md
- jumpscale/core/config/config.py
> Automaticly generate private key if missing

- jumpscale/clients/gdrive/__init__.py
- jumpscale/clients/gdrive/gdrive.py
Part of https://github.com/js-next/js-ng/issues/26
> add google drive client

- jumpscale/clients/git/__init__.py
- jumpscale/clients/git/git.py
- jumpscale/tools/git/__init__.py
- pyproject.toml
https://github.com/js-next/js-ng/issues/26
> add git client and tools

- jumpscale/core/logging/logging.py
- jumpscale/sals/fs/fs.py
- tests/base_tests.py
- tests/sals/fs/test_fs.py
----------------------------------------------------------------------
Ran 14 tests in 0.975s
OK (SKIP=1)
> Dev tests fs

- jumpscale/clients/docker/__init__.py
- jumpscale/clients/docker/docker.py
- poetry.lock
- pyproject.toml
> Adds containers manager

- jumpscale/core/dirs/__init__.py
- jumpscale/core/dirs/dirs.py
- jumpscale/tools/jinja2/__init__.py
https://github.com/js-next/js-ng/issues/141
https://github.com/js-next/js-ng/issues/171
> add dirs and jinja2

- jumpscale/core/base/fields.py
- tests/core/base/test_field.py
working on enhancements in
https://github.com/js-next/js-ng/issues/140 
Add the Email, path, URL, tel, IPaddress, DateTime, date, time, duration types to our fields
> Development datatypes

- jumpscale/core/executors/local.py
- jumpscale/sals/process/__init__.py
- poetry.lock
- pyproject.toml
> Adds fix/doc sals process

- jumpscale/core/base/fields.py
- tests/core/base/test_factory.py
Adding test including an object with our new fields
> adding tests for object using our  new fields

- jumpscale/entry_points/jsng.py
- jumpscale/install/Dockerfile
> Adds js-ng Dockerfile

- jumpscale/core/base/factory.py
- jumpscale/sals/fs/fs.py
- jumpscale/servers/openresty/__init__.py
- jumpscale/servers/openresty/location.py
- jumpscale/servers/openresty/server.py
- jumpscale/servers/openresty/templates/letsencrypt_challenge_location.conf
- jumpscale/servers/openresty/templates/location.conf
- jumpscale/servers/openresty/templates/location_lapis.conf
- jumpscale/servers/openresty/templates/location_proxy.conf
- jumpscale/servers/openresty/templates/location_spa.conf
- jumpscale/servers/openresty/templates/location_static.conf
- jumpscale/servers/openresty/templates/nginx.conf
- jumpscale/servers/openresty/templates/website.conf
- jumpscale/servers/openresty/utils.py
- jumpscale/tools/git/__init__.py
- jumpscale/tools/jinja2/__init__.py
https://github.com/js-next/js-ng/issues/137
> openresty init

- jumpscale/sals/fs/__init__.py
working on issue
https://github.com/js-next/js-ng/issues/188
I have updated the docs and added examples
> working on docs for sal fs

- jumpscale/clients/docker/docker.py
- jumpscale/entry_points/usershell.py
- jumpscale/god.py
- jumpscale/sals/process/__init__.py
- pyproject.toml
> Adds container_install and docs

- jumpscale/tools/startupcmd/__init__.py
- jumpscale/tools/startupcmd/startupcmd.py
- tests/servers/openresty/test_openresty.py
- tests/tools/startupcmd/test_startupcmd.py
https://github.com/js-next/js-ng/issues/201
> add startup commands

- jumpscale/clients/zerotier/__init__.py
- jumpscale/clients/zerotier/zerotier.py
https://github.com/js-next/js-ng/issues/158
> add zerotier client

- docs/wiki/research/nginx_ssl.md
https://github.com/js-next/js-ng/issues/212
> add nginx ssl research

- jumpscale/tools/profiler/__init__.py
- poetry.lock
- pyproject.toml
> Adds method visualized profiler

- docs/notebooks/config.ipynb
- docs/notebooks/dirs.ipynb
- docs/notebooks/dns.ipynb
- docs/notebooks/exceptions.ipynb
- docs/notebooks/fake.ipynb
- docs/notebooks/http.ipynb
- docs/notebooks/plateform.ipynb
- docs/notebooks/process.ipynb
- docs/notebooks/random_names.ipynb
- docs/notebooks/terminaltable.ipynb
working on issue 
https://github.com/js-next/js-ng/issues/198
I have added more examples including dirs, config , exceptions (that shows better exceptions), and more on data like fake, platform, random_names, terminaltables, proccess , dnstool, http tool
> add more examples for notebook

- jumpscale/core/config/config.py
issue: https://github.com/js-next/js-ng/issues/283
> add get and set functions in config

- jumpscale/core/base/fields.py
- jumpscale/tools/schemac/plugins/jsng.py
- pyproject.toml
Cleanup redundant stuff in map loading
See: #279
> Add types for guid and IPAddr

- jumpscale/install/Dockerfile
see https://github.com/js-next/js-ng/issues/303
> install nginx and tmux

- .gitignore
- jumpscale/clients/explorer/__init__.py
- jumpscale/core/identity/__init__.py
- jumpscale/sals/process/__init__.py
- jumpscale/servers/threebot/threebot.py
https://github.com/js-next/js-sdk/issues/2
> Add admin dashboard to threebot

- jumpscale/clients/explorer/__init__.py
- jumpscale/clients/explorer/users.py
- jumpscale/core/base/factory.py
- jumpscale/core/identity/__init__.py
> Update indetity to deal with _tid better

- jumpscale/install/Dockerfile
- jumpscale/install/codeserver-install.sh
Fixes https://github.com/threefoldtech/js-ng/issues/307
> Added codeserver script to docker image

- jumpscale/entry_points/usershell.py
Don't crash when empty command is given
Don't crash when fuction/module are missing docstring
Errors are considering expert mode
> Harden usershell

- jumpscale/entry_points/usershell.py
- jumpscale/threesdk/settings.py
- jumpscale/threesdk/threebot.py
When using 3sdk in expert mode we print full stacktraces
In expert mode mounting of codedir is implied
> 3sdk expert mode exceptions handling and code mount

- jumpscale/threesdk/container.py
- jumpscale/threesdk/settings.py
- jumpscale/threesdk/threebot.py
> Add 3sdk shell and jsng command

- jumpscale/core/application/application.py
- jumpscale/core/logging/logging.py
- jumpscale/shell/config.py
see https://github.com/threefoldtech/js-ng/issues/313
> fix logging and alerts

- jumpscale/sals/unix/__init__.py
- jumpscale/sals/unix/user.py
needed by: https://github.com/threefoldtech/js-sdk/pull/57
> add unix sal

- jumpscale/sals/process/__init__.py
- Refactor the implementation to get_process_by_port
- add new method to check if the port is listening or no
> fix get process by port

- poetry.lock
- pyproject.toml
fixes #351
I'm not familiar with how poetry works, is it correct to have included the poetry.lock file in this PR ?
> add pycparser and zipp to the list of dependecies

- jumpscale/clients/sshclient/sshclient.py
- jumpscale/clients/sshkey/sshkey.py
- jumpscale/entry_points/jsync.py
reviewing and updating some docs regarding issue https://github.com/threefoldtech/js-ng/issues/344
> Checking and updating docs for sskey, sshclient  and jsync

- jumpscale/install/Dockerfile
- jumpscale/install/codeserver-install.py
- jumpscale/install/codeserver-install.sh
Will be on codeserver package installation instead
See https://github.com/threefoldtech/js-sdk/issues/62
> Removed codeserver installation from docker image

- jumpscale/clients/redis/redis.py
- jumpscale/core/db/__init__.py
- jumpscale/core/logging/logging.py
- jumpscale/tools/alerthandler/alerthandler.py
see https://github.com/threefoldtech/js-ng/issues/345
> handle when redis is not running

- jumpscale/core/base/factory.py
> find form disk as well as memory in storedfactory

- jumpscale/tools/git/__init__.py
issue : https://github.com/threefoldtech/js-sdk/issues/103
> Raise exception with stderr

- jumpscale/core/base/fields.py
- jumpscale/core/base/meta.py
Resolves #356.
Appends the field name to the error message.
> Add the field name to the validation error messages

- tests/core/base/test_stored_factory.py
> test the existence of the name in the exception message

- jumpscale/core/config/config.py
- jumpscale/entry_points/jsng.py
> Allow configuring ipython as default shell

- jumpscale/install/Dockerfile
- jumpscale/install/codeserver-install.py
Fixing https://github.com/threefoldtech/js-ng/issues/84
> Created js-ng lightweight docker image

- jumpscale/data/types/types.py
> Add guid to data.types required for schemas

- jumpscale/threesdk/identitymanager.py
> Don't use j inside 3sdk it does not work in the bundled pyinstaller

- jumpscale/data/encryption/mnemonic.py
Just replaced the methods with the jsx ones
> Existing implementation was not 100% compatible with jsx version

- jumpscale/sals/process/__init__.py
Solves https://github.com/threefoldtech/js-sdk/issues/216
> Fix looking for processes on osx

- jumpscale/sals/process/__init__.py
> makes is_port_listening works on unix and macosx

- jumpscale/threesdk/identitymanager.py
> fix for identity if user not on explorer

- .github/workflows/jsng-ci.yml
- jumpscale/core/executors/tmux.py
- jumpscale/sals/process/__init__.py
- tests/base_tests.py
- tests/clients/docker/test_docker.py
- tests/clients/test_docker_client.py
- tests/sals/process/test_process.py
> Add sals.process tests 

- tests/clients/redis/test_redis.py
- tests/core/base/test_store_redis.py
- tests/core/base/test_stored_factory.py
- tests/core/config/test_config.py
- Add tests for redis client
- Add tests for jsng config
- Add tests for redis store
- Modify stored factory tests to work with all stores
> Add more tests for redis client, store and config

- jumpscale/core/base/factory.py
- jumpscale/core/base/meta.py
Add `__str__` implementation to `Base` and `StoredFactory`.
Add `__str__` implementation to `Base` and `StoredFactory`.
#261.
> base: readable string for factory and base objects

- jumpscale/core/base/store/__init__.py
- tests/core/base/test_stored_factory.py
Ignore any item in location name_list if it's `None`.
This will allow to create instances from a base which contains sub-factories without a parent factory like:
```python
from enum import Enum
from jumpscale.core.base import Base, StoredFactory, fields
class Address(Base):
x = fields.Integer()
name = fields.String()
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.x = 123
class Wallet(Base):
ID = fields.Integer(required=True)
origin = fields.Typed(dict, default=dict)
addresses = fields.Factory(Address)
key = fields.Bytes()
email = fields.Email()
url = fields.URL(required=False, allow_empty=True)
data = fields.Json(allow_empty=False)
class Permission(Base):
is_admin = fields.Boolean()
class UserType(Enum):
USER = "user"
ADMIN = "admin"
class Greeter:
def …
```
> base: fix store location with None in name_list

- docs/wiki/editor_setup.md
Mention how to remove old venv
- editor_setup.md
None
> docs: mention how to remove old venv in ~/.cache

- README.md
- docs/wiki/testing_contribution.md
- tests/tools/startupcmd/test_startupcmd.py
- Add testing contribution docs
- Fix test_startupcmd sleep time
- Add link to codecov badge
> Add testing contribution docs

- docs/wiki/_sidebar.md
- docs/wiki/tutorials/githubactions-ci.md
Describe the changes introduced by this PR and what does it affect
> Add how to write a test to docs sidebar

- jumpscale/sals/fs/__init__.py
Implement _is_broken_link_ and _rm_broken_link_ functions
> Implement is_broken_link and rm_broken_link

- jumpscale/install/Dockerfile
Describe the changes introduced by this PR and what does it affect
> Fixes ci for jsng

- CODEOWNERS
> Add Hanafy as codeowner

- jumpscale/servers/gedis/server.py
Remove `better_exceptions` unused import.
Updated `gedis/server.py`.
None
> remove unused import in gedis server module

- jumpscale/clients/gedis/gedis.py
- jumpscale/sals/fs/__init__.py
- jumpscale/servers/gedis/systemactor.py
- jumpscale/tools/codeloader/__init__.py
- tests/servers/gedis/test_actors/memory_profiler.py
- tests/servers/gedis/test_actors/test_actor.py
- tests/servers/gedis/test_actors/test_reloading.py
- tests/servers/gedis/test_actors/test_reloading_changed.py
- tests/servers/gedis/test_gedis.py
Support reloading of actor modules in `systemactor.register_actor`
* Added force reload option to:
* `codeloader`
* `systemactor.register_actor`
* gedis client `reload`
* Arranged and added more tests
> gedis: support reloading of actor modules

- pyproject.toml
Bump version to 11.0b6
* `pyproject.toml`
> bump version to 11.0b6

- jumpscale/sals/fs/__init__.py
> Add makedirs alias

- docs/api/jumpscale/clients/base.html
- docs/api/jumpscale/clients/docker/docker.html
- docs/api/jumpscale/clients/gedis/gedis.html
- docs/api/jumpscale/clients/git/git.html
- docs/api/jumpscale/clients/redis/redis.html
- docs/api/jumpscale/clients/sshclient/sshclient.html
- docs/api/jumpscale/clients/sshkey/sshkey.html
- docs/api/jumpscale/clients/zdb/client.html
- docs/api/jumpscale/core/base/factory.html
- docs/api/jumpscale/core/base/fields.html
- docs/api/jumpscale/core/base/meta.html
- docs/api/jumpscale/core/events/index.html
- docs/api/jumpscale/data/bcdb/models/base.html
- docs/api/jumpscale/data/time/index.html
- docs/api/jumpscale/sals/fs/index.html
- docs/api/jumpscale/sals/process/index.html
- docs/api/jumpscale/servers/gedis/server.html
- docs/api/jumpscale/servers/gedis_http/index.html
- docs/api/jumpscale/servers/openresty/location.html
- docs/api/jumpscale/servers/openresty/server.html
- docs/api/jumpscale/servers/rack/rack.html
- docs/api/jumpscale/tools/codeloader/index.html
- docs/api/jumpscale/tools/jinja2/index.html
- docs/api/jumpscale/tools/schemac/index.html
- docs/api/jumpscale/tools/startupcmd/startupcmd.html
- Generate docs for jsng
- make docs
> generate docs for jsng

- docs/api/jumpscale/clients/base.html
- docs/api/jumpscale/clients/docker/docker.html
- docs/api/jumpscale/clients/gedis/gedis.html
- docs/api/jumpscale/clients/git/git.html
- docs/api/jumpscale/clients/redis/redis.html
- docs/api/jumpscale/clients/sshclient/sshclient.html
- docs/api/jumpscale/clients/sshkey/sshkey.html
- docs/api/jumpscale/clients/zdb/client.html
- docs/api/jumpscale/core/base/factory.html
- docs/api/jumpscale/core/base/fields.html
- docs/api/jumpscale/core/base/meta.html
- docs/api/jumpscale/core/events/index.html
- docs/api/jumpscale/data/time/index.html
- docs/api/jumpscale/sals/process/index.html
- docs/api/jumpscale/servers/gedis/server.html
- docs/api/jumpscale/servers/gedis_http/index.html
- docs/api/jumpscale/servers/openresty/location.html
- docs/api/jumpscale/servers/openresty/server.html
- docs/api/jumpscale/servers/rack/rack.html
- docs/api/jumpscale/tools/codeloader/index.html
- docs/api/jumpscale/tools/jinja2/index.html
- docs/api/jumpscale/tools/schemac/index.html
- docs/api/jumpscale/tools/startupcmd/startupcmd.html
> generate new jsng docs

- Makefile
- README.md
- docs/tests/README.md
- docs/tests/clients/docker/test_docker.md
- docs/tests/clients/redis/test_redis.md
- docs/tests/core/base/test_field.md
- docs/tests/core/base/test_fields_with_base.md
- docs/tests/core/base/test_store_redis.md
- docs/tests/core/config/test_config.md
- docs/tests/sals/process/test_process.md
- docs/tests/servers/gedis/test_gedis.md
- docs/wiki/testing_contribution.md
- jumpscale/sals/fs/__init__.py
- jumpscale/sals/testdocs/__init__.py
- tests/clients/docker/test_docker.py
- tests/clients/redis/test_redis.py
- tests/core/base/test_fields_with_base.py
- tests/core/base/test_store_redis.py
- tests/core/config/test_config.py
- tests/sals/process/test_process.py
- tests/servers/gedis/test_gedis.py
- Add SAL testdocs
- Fix tests docstrings.
- Generate tests docs
- Add testdocs usage to docs
#482
> Add SAL for test docs

- jumpscale/sals/testdocs/__init__.py
Fix tests relative paths in testdoc SAL
#482
> Fix tests relative paths in testdoc SAL

- docs/api/jumpscale/servers/gedis_http/index.html
- pyproject.toml
Bump version and update docs
* Updated docs (`make docs`)
* Updated `pyproject.toml` with the new version
> bump version to 11.0b11

- docs/wiki/README.md
- docs/wiki/_sidebar.md
- docs/wiki/editor_setup.md
- docs/wiki/stores.md
- docs/wiki/tutorials/startup_commands.md
- docs/wiki/tutorials/tmux.md
Fix and update wiki links and content
- Fix some error related to issue #459
Fixes #459 #wiki
> Update and Fix Wiki

- docs/api/jumpscale/clients/base.html
- docs/api/jumpscale/core/base/meta.html
- docs/api/jumpscale/data/bcdb/models/base.html
- docs/api/jumpscale/sals/fs/index.html
- docs/api/jumpscale/tools/git/index.html
> generate new docs for jsng

- docs/tests/README.md
- jumpscale/sals/testdocs/__init__.py
- Fix repeated test docs
- cleanup testdocs sal
- regenerate the docs
#551
> fix test docs

- docs/wiki/installation.md
Update installation docs and remove any reference to `poetry update`.
`installation.md` in wiki.
> update installation docs in wiki

- jumpscale/servers/gedis/server.py
Remove gedis signal handler.
https://github.com/threefoldtech/js-ng/issues/558
> Remove gedis signal handler

- jumpscale/entry_points/jsng.py
Add Option to enable/disable monkey patch when running jsng
#533
> Add option to disable gevent monkey patching

- docs/tests/README.md
- docs/tests/core/base/test_store_etcd.md
- docs/tests/core/base/test_store_mongo.md
- tests/core/base/test_store_etcd.py
- tests/core/base/test_store_mongo.py
- tests/core/base/test_stored_factory.py
- Add basic test for stored etcd
-  Add basic test for stored etcd
https://github.com/threefoldtech/js-ng/issues/544
> Update stored factory tests

- .github/workflows/jsng-ci.yml
- tests/core/base/test_store_etcd.py
- tests/core/base/test_store_mongo.py
- tests/core/base/test_store_redis.py
- tests/core/base/test_stored_factory.py
Describe the changes introduced by this PR and what does it affect
> Add waits to servers to start

- README.md
- jumpscale/clients/sshclient/sshclient.py
- jumpscale/clients/sshkey/sshkey.py
- jumpscale/data/hash/hash.py
- jumpscale/data/idgenerator/idgenerator.py
- jumpscale/data/random_names/__init__.py
- jumpscale/data/serializers/json.py
- jumpscale/data/tarfile/tar_file.py
- jumpscale/data/types/pritypes.py
- jumpscale/sals/hostsfile/__init__.py
- jumpscale/servers/openresty/location.py
- jumpscale/shell/config.py
- jumpscale/tools/console/__init__.py
- jumpscale/tools/startupcmd/startupcmd.py
- jumpscale/tools/syncer/__init__.py
- pyproject.toml
- tests/sals/process/test_process.py
- Bump version to 12.0
- https://github.com/threefoldtech/js-ng/issues/625
> release 12.0

- pyproject.toml
release 12.0.0
- https://github.com/threefoldtech/js-ng/issues/625
> release 12.0.0
